#!/usr/bin/env bash


[[ -z $1 ]]  && echo "Usage: _shorten_link URL" && exit 1

curl -s -H "Authorization: Bearer $BITLY_ACCESS"  -H 'Content-Type: application/json'  -X POST  -d "{\"long_url\": \"$1\"}" https://api-ssl.bitly.com/v4/shorten |
python -m json.tool |grep '"id"' |awk '{print$2}' |tr '",' ' '
