#!/bin/bash

path="$iosys/time" 
[  -z $1 ] && FILE=$(ls -tr $path --format=single-column|tail -n 1) ||
	FILE=$(ls -tr $path --format=single-column|tail -n $1 | head -n 1)

echo "$path/$FILE"
TYPE=$(file "$path/$FILE" | gawk '{print $3}')
echo "File Type $TYPE"

[[ $TYPE = "Excel" ]] && libreoffice "$path/$FILE" ||
zathura "$path/$FILE"
