#!/bin/bash

[ ! -v path ] &&  path="$ZATH_PREF/time" || echo "set to $path"
[  -z $1 ] && FILE=$(ls -tr $path --format=single-column|tail -n 1) ||
	FILE=$(ls -tr $path --format=single-column|tail -n $1 | head -n 1)

echo "$path/$FILE"
TYPE=$(file "$path/$FILE" | gawk '{print $3}')
echo "File Type $TYPE"


[[ $TYPE = "image" ]] && eog "$path/$FILE" || ( 
[[ $TYPE = "Excel" ]] && libreoffice "$path/$FILE" )||
#zathura "$path/$FILE"
xdg-open "$path/$FILE"
